import { useEffect, useMemo, useRef, useState } from 'react'
import { CalendarDays, ChevronRight, CircleUserRound, Clock3, MapPin, Mountain, Plus, Route, Search, Users, X } from 'lucide-react'
import { demoRides } from './data'
import { geocodePlace, loadKakaoMaps } from './kakao'
import { requestCourseCandidates } from './services'
import type { Coordinate, Ride, RouteCandidate } from './types'

type Tab = 'home' | 'search' | 'create' | 'my' | 'profile'
const fmt = (value: string) => new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const routeColors = ['#087458', '#ef7d5f', '#4e65c5']

function CourseMap({ routes, selected = 0, label = '코스 지도' }: { routes: Coordinate[][]; selected?: number; label?: string }) {
  const container = useRef<HTMLDivElement>(null); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [message, setMessage] = useState('카카오맵 불러오는 중…')
  useEffect(() => {
    let active = true; setStatus('loading')
    loadKakaoMaps().then(kakao => {
      if (!active || !container.current || !routes.some(route => route.length)) return
      const first = routes.find(route => route.length)![0]; const map = new kakao.maps.Map(container.current, { center: new kakao.maps.LatLng(first.lat, first.lng), level: 8 }); const bounds = new kakao.maps.LatLngBounds()
      routes.forEach((route, index) => { const path = route.map(point => { const latLng = new kakao.maps.LatLng(point.lat, point.lng); bounds.extend(latLng); return latLng }); new kakao.maps.Polyline({ path, strokeWeight: index === selected ? 7 : 4, strokeColor: routeColors[index] ?? '#59666f', strokeOpacity: index === selected ? 0.95 : 0.55 }).setMap(map) })
      const route = routes[selected] ?? routes[0]; if (route?.length) { new kakao.maps.Marker({ position: new kakao.maps.LatLng(route[0].lat, route[0].lng), map, title: '출발' }); const last = route[route.length - 1]; new kakao.maps.Marker({ position: new kakao.maps.LatLng(last.lat, last.lng), map, title: '도착' }) }
      map.setBounds(bounds); active && setStatus('ready')
    }).catch(error => { if (active) { setStatus('error'); setMessage(error instanceof Error ? error.message : '지도를 불러오지 못했습니다.') } }); return () => { active = false }
  }, [routes, selected])
  return <div className={`map live-map ${status === 'error' ? 'map-error' : ''}`} ref={container} aria-label={label}>{status !== 'ready' && <div className="map-state"><b>{status === 'error' ? '지도를 표시할 수 없어요' : message}</b>{status === 'error' && <small>{message}<br/>카카오 JavaScript SDK 도메인에 현재 주소를 등록해 주세요.</small>}</div>}{status === 'ready' && <span className="map-label">카카오맵 · {label}</span>}</div>
}

function RideCard({ ride, onOpen }: { ride: Ride; onOpen: () => void }) {
  return <button className="ride-card" onClick={onOpen}><div className="ride-date"><CalendarDays size={16}/>{fmt(ride.startsAt)}</div><h3>{ride.title}</h3><p>{ride.course.startName} · {ride.course.distanceKm}km · 상승 {ride.course.elevationM}m</p><div className="ride-meta"><span><Users size={16}/>{ride.members.length}/{ride.capacity}</span><span>{ride.paceKmh}km/h</span><span className="open">{ride.status}</span><ChevronRight size={18}/></div></button>
}

function RideDetail({ ride, onBack }: { ride: Ride; onBack: () => void }) {
  const [joined, setJoined] = useState(false)
  return <section className="page detail"><button className="back" onClick={onBack}>← 목록으로</button><CourseMap routes={[ride.course.coordinates]} label={ride.course.title}/><div className="detail-head"><div><span className="eyebrow">{ride.status}</span><h1>{ride.title}</h1><p>{fmt(ride.startsAt)}</p></div><button className={joined ? 'secondary' : 'primary'} onClick={() => setJoined(!joined)}>{joined ? '참여 취소' : '라이딩 참여'}</button></div><div className="stat-grid"><span><Route/>{ride.course.distanceKm} km<small>거리</small></span><span><Mountain/>{ride.course.elevationM} m<small>누적 상승</small></span><span><Clock3/>{ride.paceKmh} km/h<small>목표 평속</small></span></div><article className="info"><h2>집합 장소</h2><p><MapPin size={17}/>{ride.meetingNote}</p></article><article className="info"><h2>코스 정차 지점</h2>{ride.course.stops.map(stop => <p key={stop.id}><span className="dot"/>{stop.name}<em>{stop.kind}{stop.selected ? ' · 확정' : ''}</em></p>)}</article><article className="info"><h2>참여 라이더 {ride.members.length}명</h2><div className="avatars">{ride.members.map(member => <span key={member.id}>{member.name.slice(0, 1)}</span>)}</div></article></section>
}

function CommonRideFields() {
  return <><div className="two"><label>출발 일시<input required type="datetime-local"/></label><label>목표 평속<input required type="number" min="5" max="60" step="0.1" placeholder="예: 24.5"/><small>km/h</small></label></div><label>모집 인원<input required type="number" min="2" max="50" defaultValue="6"/></label><label>부가 설명 <span className="optional">선택</span><textarea rows={3} placeholder="준비물, 라이딩 성격, 주의사항 등을 적어주세요."/></label></>
}

function CandidateResults({ candidates, onReset, onCreated }: { candidates: RouteCandidate[]; onReset: () => void; onCreated: () => void }) {
  const [selected, setSelected] = useState(0)
  return <section className="candidate-results"><div className="result-head"><div><span className="eyebrow">고도 데이터 검증 완료</span><h2>추천 코스 {candidates.length}개</h2></div><button className="text-button" onClick={onReset}>조건 수정</button></div><CourseMap routes={candidates.map(candidate => candidate.coordinates)} selected={selected} label="추천 후보 비교"/><div className="candidate-list">{candidates.map((candidate, index) => <button key={candidate.id} className={`candidate-card ${selected === index ? 'selected' : ''}`} onClick={() => setSelected(index)}><span className="route-swatch" style={{ background: routeColors[index] }}/><div><b>{candidate.title}</b><p>{candidate.summary}</p><small>{candidate.distanceKm}km · 상승 {candidate.elevationM}m · km당 {candidate.climbRate}m</small></div><span className="verified">검증됨</span></button>)}</div><button className="primary wide" onClick={onCreated}>선택한 코스로 방 만들기</button></section>
}

function CreateRide({ onCreated }: { onCreated: () => void }) {
  const [mode, setMode] = useState<'ai' | 'manual'>('ai'); const [tripType, setTripType] = useState<'round' | 'oneway'>('round'); const [candidates, setCandidates] = useState<RouteCandidate[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [manualDone, setManualDone] = useState(false)
  const submitAi = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); try { const place = await geocodePlace(String(form.get('startName'))); const result = await requestCourseCandidates({ start: { lat: place.lat, lng: place.lng }, startName: place.name, distanceKm: Number(form.get('distanceKm')), uphill: String(form.get('uphill')) as 'low' | 'medium' | 'high', tripType }); setCandidates(result) } catch (reason) { setError(reason instanceof Error ? reason.message : '코스를 추천하지 못했습니다. 잠시 후 다시 시도해 주세요.') } finally { setLoading(false) } }
  if (manualDone) return <section className="result"><div className="success">✓</div><h1>라이딩 정보를 저장했어요</h1><p>입력한 내용으로 모집 방을 만들 준비가 됐습니다.</p><button className="primary wide" onClick={onCreated}>라이딩 보기</button></section>
  return <section className="page create-page"><h1>라이딩 만들기</h1><p className="sub">AI 추천을 받거나 모든 정보를 직접 입력할 수 있어요.</p><div className="mode-cards"><button className={mode === 'ai' ? 'active' : ''} onClick={() => { setMode('ai'); setCandidates([]) }}><Route/><b>AI 코스 추천</b><small>거리·업힐 조건으로 3개 추천</small></button><button className={mode === 'manual' ? 'active' : ''} onClick={() => { setMode('manual'); setCandidates([]) }}><MapPin/><b>모두 직접 입력</b><small>출발·도착·정차 정보를 수동 작성</small></button></div>
    {mode === 'ai' && candidates.length ? <CandidateResults candidates={candidates} onReset={() => setCandidates([])} onCreated={onCreated}/> : mode === 'ai' ? <form onSubmit={submitAi}><label>출발 지점<input name="startName" required placeholder="예: 여의나루역, 광나루 자전거공원"/></label><div className="two"><label>희망 거리<input name="distanceKm" required type="number" min="5" max="200" defaultValue="40"/><small>km</small></label><label>희망 업힐 정도<select name="uphill" defaultValue="medium"><option value="low">평지 위주</option><option value="medium">적당한 업힐</option><option value="high">업힐 도전</option></select></label></div><fieldset><legend>라이딩 유형</legend><div className="segmented"><button type="button" className={tripType === 'round' ? 'active' : ''} onClick={() => setTripType('round')}>왕복·순환</button><button type="button" className={tripType === 'oneway' ? 'active' : ''} onClick={() => setTripType('oneway')}>편도</button></div></fieldset><CommonRideFields/>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary wide" type="submit" disabled={loading}>{loading ? 'AI 후보 생성·고도 검증 중…' : '추천 코스 3개 찾기'}</button></form> : <form onSubmit={event => { event.preventDefault(); setManualDone(true) }}><label>라이딩 제목<input required placeholder="예: 주말 한강 라이딩"/></label><label>출발 지점<input required placeholder="집합 장소를 입력하세요"/></label><label>도착 지점<input required placeholder="도착 장소를 입력하세요"/></label><div className="two"><label>예상 거리<input required type="number" min="1" step="0.1"/><small>km</small></label><label>정차 횟수<input required type="number" min="0" max="20" defaultValue="1"/></label></div><label>코스 파일 <span className="optional">선택</span><input type="file" accept=".gpx,application/gpx+xml"/></label><CommonRideFields/><button className="primary wide" type="submit">직접 입력으로 방 만들기</button></form>}
  </section>
}

export default function App() {
  const [tab, setTab] = useState<Tab>('home'); const [selected, setSelected] = useState<Ride | null>(null); const [query, setQuery] = useState(''); const rides = useMemo(() => demoRides.filter(ride => ride.title.includes(query) || ride.course.startName.includes(query)), [query])
  const content = selected ? <RideDetail ride={selected} onBack={() => setSelected(null)}/> : tab === 'create' ? <CreateRide onCreated={() => { setTab('home'); setSelected(demoRides[0]) }}/> : tab === 'profile' ? <section className="page profile"><CircleUserRound size={66}/><h1>라이더 프로필</h1><p className="sub">로그인하면 코스와 라이딩 이력을 관리할 수 있어요.</p><button className="primary wide">카카오로 시작하기</button><button className="secondary wide">이메일로 로그인</button><article className="notice"><b>노쇼 정책</b><p>라이딩 종료 후 참여자 투표에서 최소 3표·과반으로 확정된 경우에만 기록됩니다.</p></article></section> : <section className="page"><div className="hero"><span>함께 달리는 더 안전한 라이딩</span><h1>오늘, 누구와<br/>어디로 달릴까요?</h1><button className="hero-action" onClick={() => setTab('create')}><Plus size={18}/>라이딩 만들기</button></div><div className="search"><Search size={18}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="지역 또는 코스 검색"/><button aria-label="검색어 지우기" onClick={() => setQuery('')}><X size={16}/></button></div><div className="section-title"><h2>{tab === 'search' ? '검색 결과' : '지금 모집 중인 라이딩'}</h2><button onClick={() => setTab('search')}>전체 보기</button></div><div className="list">{rides.map(ride => <RideCard key={ride.id} ride={ride} onOpen={() => setSelected(ride)}/>)}{!rides.length && <p className="empty">조건에 맞는 라이딩이 없습니다.</p>}</div></section>
  return <main className="app-shell"><header><button onClick={() => { setTab('home'); setSelected(null) }} className="logo">RIDEMATE<span>라이딩 메이트</span></button><button className="bell" aria-label="알림">●</button></header>{content}{!selected && <nav>{([['home', '홈'], ['search', '탐색'], ['create', '만들기'], ['my', '내 라이딩'], ['profile', '프로필']] as [Tab, string][]).map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'current' : ''}>{id === 'create' ? <Plus size={22}/> : id === 'search' ? <Search size={21}/> : id === 'profile' ? <CircleUserRound size={21}/> : id === 'my' ? <CalendarDays size={21}/> : <Route size={21}/>}<span>{label}</span></button>)}</nav>}</main>
}
