import { useEffect, useMemo, useRef, useState } from 'react'
import { CalendarDays, ChevronRight, CircleUserRound, Clock3, MapPin, Mountain, Plus, Route, Search, ShieldCheck, Users, X } from 'lucide-react'
import { createUserWithEmailAndPassword, onAuthStateChanged, sendEmailVerification, signInWithEmailAndPassword, signOut, type User } from 'firebase/auth'
import AdminPanel from './AdminPanel'
import { auth } from './firebase'
import { geocodePlace, loadKakaoMaps } from './kakao'
import { bootstrapAdmin, createRidePlan, listMyRidePlans, requestCourseCandidates } from './services'
import type { Coordinate, ElevationPoint, Ride, RouteCandidate } from './types'

type Tab = 'home' | 'search' | 'create' | 'my' | 'profile'
const fmt = (value: string) => new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
const routeColors = ['#087458', '#ef7d5f', '#4e65c5']
type SavedPlan = { id: string; title: string; purpose: 'group' | 'solo'; distanceKm: number; elevationM: number; startName: string; createdAt: string }
const readPlans = (): SavedPlan[] => { try { return JSON.parse(localStorage.getItem('ridemate-plans') ?? '[]') as SavedPlan[] } catch { return [] } }
const savePlan = (plan: Omit<SavedPlan, 'id' | 'createdAt'>) => { if(auth?.currentUser) void createRidePlan({title:plan.title,purpose:plan.purpose,startName:plan.startName,distanceKm:plan.distanceKm,elevationM:plan.elevationM}).catch(()=>undefined); const next = [{ ...plan, id: crypto.randomUUID(), createdAt: new Date().toISOString() }, ...readPlans()]; localStorage.setItem('ridemate-plans', JSON.stringify(next.slice(0, 30))) }

function CourseMap({ routes, selected = 0, label = '코스 지도' }: { routes: Coordinate[][]; selected?: number; label?: string }) {
  const container = useRef<HTMLDivElement>(null); const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [message, setMessage] = useState('카카오맵 불러오는 중…')
  useEffect(() => {
    let active = true; setStatus('loading')
    loadKakaoMaps().then(kakao => {
      if (!active || !container.current || !routes.some(route => route.length)) return
      const first = routes.find(route => route.length)![0]; const map = new kakao.maps.Map(container.current, { center: new kakao.maps.LatLng(first.lat, first.lng), level: 8 }); const bounds = new kakao.maps.LatLngBounds()
      routes.forEach((route, index) => { const path = route.map(point => { const latLng = new kakao.maps.LatLng(point.lat, point.lng); bounds.extend(latLng); return latLng }); new kakao.maps.Polyline({ path, strokeWeight: index === selected ? 7 : 4, strokeColor: routeColors[index] ?? '#59666f', strokeOpacity: index === selected ? 0.95 : 0.55 }).setMap(map) })
      const route = routes[selected] ?? routes[0]; if (route?.length) { new kakao.maps.Marker({ position: new kakao.maps.LatLng(route[0].lat, route[0].lng), map, title: '출발' }); const last = route[route.length - 1]; new kakao.maps.Marker({ position: new kakao.maps.LatLng(last.lat, last.lng), map, title: '도착' }) }
      map.setBounds(bounds); if (active) setStatus('ready')
    }).catch(error => { if (active) { setStatus('error'); setMessage(error instanceof Error ? error.message : '지도를 불러오지 못했습니다.') } }); return () => { active = false }
  }, [routes, selected])
  return <div className={`map live-map ${status === 'error' ? 'map-error' : ''}`} ref={container} aria-label={label}>{status !== 'ready' && <div className="map-state"><b>{status === 'error' ? '지도를 표시할 수 없어요' : message}</b>{status === 'error' && <small>{message}<br/>카카오 JavaScript SDK 도메인에 현재 주소를 등록해 주세요.</small>}</div>}{status === 'ready' && <><span className="map-label">카카오맵 위 · 자전거 경로</span><span className="cycle-badge">자동차 길찾기 아님 · ORS cycling</span></>}</div>
}

function ElevationChart({ points }: { points: ElevationPoint[] }) {
  if (points.length < 2) return null
  const width = 420; const height = 145; const padX = 12; const padTop = 12; const padBottom = 24; const min = Math.min(...points.map(point => point.elevationM)); const max = Math.max(...points.map(point => point.elevationM)); const range = Math.max(max - min, 1); const distance = Math.max(points.at(-1)?.distanceKm ?? 1, 1)
  const coordinates = points.map(point => ({ x: padX + point.distanceKm / distance * (width - padX * 2), y: padTop + (max - point.elevationM) / range * (height - padTop - padBottom) })); const line = coordinates.map((point, index) => `${index ? 'L' : 'M'}${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(' '); const area = `${line} L${coordinates.at(-1)!.x},${height - padBottom} L${coordinates[0].x},${height - padBottom} Z`
  return <article className="elevation-card"><div><b>고도 프로필</b><span>최저 {Math.round(min)}m · 최고 {Math.round(max)}m</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`거리 ${distance.toFixed(1)}킬로미터의 고도 그래프`}><path className="elevation-area" d={area}/><path className="elevation-line" d={line}/><text x={padX} y={height - 6}>0km</text><text x={width - padX} y={height - 6} textAnchor="end">{distance.toFixed(1)}km</text></svg></article>
}

function RideCard({ ride, onOpen }: { ride: Ride; onOpen: () => void }) {
  return <button className="ride-card" onClick={onOpen}><div className="ride-date"><CalendarDays size={16}/>{fmt(ride.startsAt)}</div><h3>{ride.title}</h3><p>{ride.course.startName} · {ride.course.distanceKm}km · 상승 {ride.course.elevationM}m</p><div className="ride-meta"><span><Users size={16}/>{ride.members.length}/{ride.capacity}</span><span>{ride.paceKmh}km/h</span><span className="open">{ride.status}</span><ChevronRight size={18}/></div></button>
}

function RideDetail({ ride, onBack }: { ride: Ride; onBack: () => void }) {
  const [joined, setJoined] = useState(false)
  return <section className="page detail"><button className="back" onClick={onBack}>← 목록으로</button><CourseMap routes={[ride.course.coordinates]} label={ride.course.title}/><div className="detail-head"><div><span className="eyebrow">{ride.status}</span><h1>{ride.title}</h1><p>{fmt(ride.startsAt)}</p></div><button className={joined ? 'secondary' : 'primary'} onClick={() => setJoined(!joined)}>{joined ? '참여 취소' : '라이딩 참여'}</button></div><div className="stat-grid"><span><Route/>{ride.course.distanceKm} km<small>거리</small></span><span><Mountain/>{ride.course.elevationM} m<small>누적 상승</small></span><span><Clock3/>{ride.paceKmh} km/h<small>목표 평속</small></span></div><article className="info"><h2>집합 장소</h2><p><MapPin size={17}/>{ride.meetingNote}</p></article><article className="info"><h2>코스 정차 지점</h2>{ride.course.stops.map(stop => <p key={stop.id}><span className="dot"/>{stop.name}<em>{stop.kind}{stop.selected ? ' · 확정' : ''}</em></p>)}</article><article className="info"><h2>참여 라이더 {ride.members.length}명</h2><div className="avatars">{ride.members.map(member => <span key={member.id}>{member.name.slice(0, 1)}</span>)}</div></article></section>
}

function RideDateTimeFields({ optional = false }: { optional?: boolean }) {
  const hours = Array.from({ length: 12 }, (_, index) => index + 1)
  return <fieldset className="date-time-fields"><legend>출발 날짜와 시간 {optional&&<span className="optional">선택</span>}</legend><div className="date-time-grid"><label className="date-field">날짜<input required={!optional} name="rideDate" type="date"/></label><label>오전·오후<select required={!optional} name="ridePeriod" defaultValue="AM"><option value="AM">오전</option><option value="PM">오후</option></select></label><label>시<select required={!optional} name="rideHour" defaultValue="8">{hours.map(hour => <option key={hour} value={hour}>{hour}시</option>)}</select></label><label>분<select required={!optional} name="rideMinute" defaultValue="00"><option value="00">00분</option><option value="10">10분</option><option value="20">20분</option><option value="30">30분</option><option value="40">40분</option><option value="50">50분</option></select></label></div><small className="field-help">{optional?'일정을 정하지 않았다면 비워두어도 됩니다.':'예: 9월 5일 · 오전 8시 30분'}</small></fieldset>
}

function CommonRideFields({ solo }: { solo: boolean }) {
  return <><RideDateTimeFields optional={solo}/><div className="two"><label>목표 평속<input name="paceKmh" required type="number" min="5" max="60" step="0.1" placeholder="예: 24.5"/><small>km/h</small></label>{solo ? <label>예상 휴식 횟수<input name="restCount" type="number" min="0" max="20" defaultValue="1"/></label> : <label>모집 인원<input name="capacity" required type="number" min="2" max="50" defaultValue="6"/></label>}</div><label>부가 설명 <span className="optional">선택</span><textarea name="description" rows={3} placeholder={solo ? '준비물, 보급 계획, 개인 목표 등을 적어주세요.' : '준비물, 라이딩 성격, 주의사항 등을 적어주세요.'}/></label></>
}

function CandidateResults({ candidates, onReset, onCreated, solo }: { candidates: RouteCandidate[]; onReset: () => void; onCreated: () => void; solo: boolean }) {
  const [selected, setSelected] = useState(0); const [saving,setSaving]=useState(false)
  const store = async () => { const candidate = candidates[selected]; const startName=candidate.startName??'AI 추천 출발지'; setSaving(true); try { if(auth?.currentUser) await createRidePlan({ title:candidate.title,purpose:solo?'solo':'group',startName,distanceKm:candidate.distanceKm,elevationM:candidate.elevationM,coordinates:candidate.coordinates,elevationProfile:candidate.elevationProfile }); else savePlan({ title: candidate.title, purpose: solo ? 'solo' : 'group', distanceKm: candidate.distanceKm, elevationM: candidate.elevationM, startName }); onCreated() } finally { setSaving(false) } }
  return <section className="candidate-results"><div className="result-head"><div><span className="eyebrow">자전거 경로·고도 검증 완료</span><h2>추천 코스 {candidates.length}개</h2></div><button className="text-button" onClick={onReset}>조건 수정</button></div><CourseMap routes={candidates.map(candidate => candidate.coordinates)} selected={selected} label="추천 후보 비교"/><ElevationChart points={candidates[selected]?.elevationProfile ?? []}/><div className="candidate-list">{candidates.map((candidate, index) => <button key={candidate.id} className={`candidate-card ${selected === index ? 'selected' : ''}`} onClick={() => setSelected(index)}><span className="route-swatch" style={{ background: routeColors[index] }}/><div><b>{candidate.title}</b><p>{candidate.summary}</p><small>{candidate.distanceKm}km · 상승 {candidate.elevationM}m · km당 {candidate.climbRate}m</small></div><span className="verified">검증됨</span></button>)}</div><button className="primary wide" disabled={saving} onClick={store}>{saving?'저장 중…':solo ? '내 라이딩 계획 저장' : '선택한 코스로 방 만들기'}</button></section>
}

function CreateRide({ onCreated }: { onCreated: () => void }) {
  const [purpose, setPurpose] = useState<'group' | 'solo'>('group'); const [mode, setMode] = useState<'ai' | 'manual'>('ai'); const [tripType, setTripType] = useState<'round' | 'oneway'>('round'); const [candidates, setCandidates] = useState<RouteCandidate[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [manualDone, setManualDone] = useState(false); const solo = purpose === 'solo'
  const submitAi = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(''); const form = new FormData(event.currentTarget); try { const place = await geocodePlace(String(form.get('startName'))); const result = await requestCourseCandidates({ start: { lat: place.lat, lng: place.lng }, startName: place.name, distanceKm: Number(form.get('distanceKm')), uphill: String(form.get('uphill')) as 'low' | 'medium' | 'high', tripType }); setCandidates(result) } catch (reason) { setError(reason instanceof Error ? reason.message : '코스를 추천하지 못했습니다. 잠시 후 다시 시도해 주세요.') } finally { setLoading(false) } }
  if (manualDone) return <section className="result"><div className="success">✓</div><h1>{solo ? '혼자 라이딩 계획을 저장했어요' : '라이딩 정보를 저장했어요'}</h1><p>{solo ? '내 라이딩에서 언제든 다시 확인할 수 있어요.' : '입력한 내용으로 모집 방을 만들 준비가 됐습니다.'}</p><button className="primary wide" onClick={onCreated}>라이딩 보기</button></section>
  return <section className="page create-page"><h1>{solo ? '혼자 라이딩 계획' : '라이딩 만들기'}</h1><p className="sub">함께 달릴 방을 만들거나 나만의 코스를 계획할 수 있어요.</p><div className="purpose-tabs" role="group" aria-label="라이딩 목적"><button className={!solo ? 'active' : ''} onClick={() => { setPurpose('group'); setCandidates([]) }}><Users/><b>함께 라이딩</b><small>라이더를 모집해요</small></button><button className={solo ? 'active' : ''} onClick={() => { setPurpose('solo'); setCandidates([]) }}><CircleUserRound/><b>혼자 라이딩</b><small>내 계획만 저장해요</small></button></div><div className="mode-cards"><button className={mode === 'ai' ? 'active' : ''} onClick={() => { setMode('ai'); setCandidates([]) }}><Route/><b>AI 코스 추천</b><small>거리·업힐 조건으로 3개 추천</small></button><button className={mode === 'manual' ? 'active' : ''} onClick={() => { setMode('manual'); setCandidates([]) }}><MapPin/><b>모두 직접 입력</b><small>출발·도착·정차 정보를 수동 작성</small></button></div>
    {mode === 'ai' && candidates.length ? <CandidateResults candidates={candidates} onReset={() => setCandidates([])} onCreated={onCreated} solo={solo}/> : mode === 'ai' ? <form onSubmit={submitAi}><label>출발 지점<input name="startName" required placeholder="예: 여의나루역, 광나루 자전거공원"/></label><div className="two"><label>희망 거리<input name="distanceKm" required type="number" min="5" max="200" defaultValue="40"/><small>km</small></label><label>희망 업힐 정도<select name="uphill" defaultValue="medium"><option value="low">평지 위주</option><option value="medium">적당한 업힐</option><option value="high">업힐 도전</option></select></label></div><fieldset><legend>라이딩 유형</legend><div className="segmented"><button type="button" className={tripType === 'round' ? 'active' : ''} onClick={() => setTripType('round')}>왕복·순환</button><button type="button" className={tripType === 'oneway' ? 'active' : ''} onClick={() => setTripType('oneway')}>편도</button></div></fieldset><CommonRideFields solo={solo}/>{error && <p className="form-error" role="alert">{error}</p>}<button className="primary wide" type="submit" disabled={loading}>{loading ? 'AI 후보 생성·자전거 경로·고도 검증 중…' : '추천 코스 3개 찾기'}</button></form> : <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); savePlan({ title: String(form.get('title')), purpose, distanceKm: Number(form.get('manualDistance')), elevationM: 0, startName: String(form.get('manualStart')) }); setManualDone(true) }}><label>라이딩 제목<input name="title" required placeholder={solo ? '예: 일요일 개인 훈련' : '예: 주말 한강 라이딩'}/></label><label>출발 지점<input name="manualStart" required placeholder="출발 장소를 입력하세요"/></label><label>도착 지점<input name="manualEnd" required placeholder="도착 장소를 입력하세요"/></label><div className="two"><label>예상 거리<input name="manualDistance" required type="number" min="1" step="0.1"/><small>km</small></label><label>정차 횟수<input required type="number" min="0" max="20" defaultValue="1"/></label></div><label>코스 파일 <span className="optional">선택</span><input type="file" accept=".gpx,application/gpx+xml"/></label><CommonRideFields solo={solo}/><button className="primary wide" type="submit">{solo ? '혼자 라이딩 계획 저장' : '직접 입력으로 방 만들기'}</button></form>}
  </section>
}

function LoginPanel() {
  const [user, setUser] = useState<User | null>(auth?.currentUser ?? null); const [isAdmin,setIsAdmin]=useState(false); const [mode, setMode] = useState<'login' | 'signup'>('login'); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => auth ? onAuthStateChanged(auth, next=>{setUser(next);if(next)void next.getIdTokenResult().then(token=>setIsAdmin(token.claims.admin===true));else setIsAdmin(false)}) : undefined, [])
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!auth) return setMessage('Firebase 연결 설정이 필요합니다.'); const form = new FormData(event.currentTarget); const email = String(form.get('email')); const password = String(form.get('password')); setBusy(true); setMessage(''); try { if (mode === 'signup') await createUserWithEmailAndPassword(auth, email, password); else await signInWithEmailAndPassword(auth, email, password) } catch (reason) { const code = (reason as { code?: string }).code; setMessage(code === 'auth/email-already-in-use' ? '이미 가입된 이메일입니다.' : code === 'auth/invalid-credential' ? '이메일 또는 비밀번호를 확인해 주세요.' : code === 'auth/weak-password' ? '비밀번호는 6자 이상 입력해 주세요.' : '로그인 처리 중 문제가 생겼습니다. 잠시 후 다시 시도해 주세요.') } finally { setBusy(false) } }
  const requestAdmin = async()=>{setBusy(true);setMessage('');try{await bootstrapAdmin();await user?.getIdToken(true);setIsAdmin(true)}catch(reason){setMessage(reason instanceof Error?reason.message:'관리자 권한을 확인하지 못했습니다.')}finally{setBusy(false)}}
  if (user) return <section className="page profile"><CircleUserRound size={66}/><h1>라이더 프로필</h1><p className="sub"><b>{user.email}</b><br/>로그인되어 있습니다.</p>{!user.emailVerified&&<button className="primary wide" onClick={()=>sendEmailVerification(user).then(()=>setMessage('인증 메일을 전송했습니다. 메일 인증 후 다시 로그인해 주세요.'))}>이메일 인증 보내기</button>}{isAdmin?<button className="admin-entry wide" onClick={()=>{window.location.search='?admin=1'}}><ShieldCheck size={18}/>관리자 페이지</button>:<button className="secondary wide" disabled={busy} onClick={requestAdmin}>관리자 권한 확인</button>}{message&&<p className="form-error">{message}</p>}<button className="secondary wide" onClick={() => auth && signOut(auth)}>로그아웃</button><article className="notice"><b>노쇼 정책</b><p>라이딩 종료 후 참여자 투표에서 최소 3표·과반으로 확정된 경우에만 기록됩니다.</p></article></section>
  return <section className="page profile login-panel"><CircleUserRound size={58}/><h1>{mode === 'login' ? '로그인' : '이메일 회원가입'}</h1><p className="sub">라이딩 참여와 계획 저장을 위해 로그인해 주세요.</p><form onSubmit={submit}><label>이메일<input required name="email" type="email" autoComplete="email" placeholder="rider@example.com"/></label><label>비밀번호<input required name="password" type="password" minLength={6} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} placeholder="6자 이상"/></label>{message && <p className="form-error" role="alert">{message}</p>}<button className="primary wide" type="submit" disabled={busy}>{busy ? '처리 중…' : mode === 'login' ? '이메일로 로그인' : '회원가입 완료'}</button></form><button className="text-button auth-switch" onClick={() => { setMode(mode === 'login' ? 'signup' : 'login'); setMessage('') }}>{mode === 'login' ? '처음이신가요? 이메일로 회원가입' : '이미 계정이 있나요? 로그인'}</button><article className="notice"><b>카카오 로그인</b><p>카카오 계정 연결은 OAuth 보안 설정 후 제공됩니다. 현재는 이메일 로그인을 이용해 주세요.</p></article></section>
}

function MyRides() {
  const [plans, setPlans] = useState(readPlans); const remove = (id: string) => { const next = plans.filter(plan => plan.id !== id); localStorage.setItem('ridemate-plans', JSON.stringify(next)); setPlans(next) }
  useEffect(()=>{if(auth?.currentUser) void listMyRidePlans().then(rows=>setPlans(rows.map(row=>({id:row.id,title:row.title,purpose:row.purpose,distanceKm:Number(row.course.distanceKm??0),elevationM:Number(row.course.elevationM??0),startName:String(row.course.startName??'-'),createdAt:row.createdAt??''})))).catch(()=>undefined)},[])
  return <section className="page"><h1>내 라이딩</h1><p className="sub">이 기기에 저장한 모집 방과 혼자 라이딩 계획입니다.</p><div className="list">{plans.map(plan => <article className="saved-plan" key={plan.id}><span>{plan.purpose === 'solo' ? '혼자 라이딩' : '함께 라이딩'}</span><button aria-label={`${plan.title} 삭제`} onClick={() => remove(plan.id)}><X size={16}/></button><h3>{plan.title}</h3><p><MapPin size={14}/>{plan.startName}</p><div><b>{plan.distanceKm}km</b><b>상승 {plan.elevationM ? `${plan.elevationM}m` : '수동 입력'}</b></div></article>)}{!plans.length && <p className="empty">아직 저장한 라이딩이 없습니다.<br/>만들기에서 첫 계획을 세워보세요.</p>}</div></section>
}

export default function App() {
  const [tab, setTab] = useState<Tab>('home'); const [selected, setSelected] = useState<Ride | null>(null); const [query, setQuery] = useState(''); const rides = useMemo<Ride[]>(() => [], [])
  if(new URLSearchParams(window.location.search).get('admin')==='1') return <main className="app-shell"><AdminPanel onClose={()=>{window.location.href=window.location.pathname}}/></main>
  const content = selected ? <RideDetail ride={selected} onBack={() => setSelected(null)}/> : tab === 'create' ? <CreateRide onCreated={() => setTab('my')}/> : tab === 'my' ? <MyRides/> : tab === 'profile' ? <LoginPanel/> : <section className="page"><div className="hero"><span>함께 달리는 더 안전한 라이딩</span><h1>오늘, 누구와<br/>어디로 달릴까요?</h1><button className="hero-action" onClick={() => setTab('create')}><Plus size={18}/>라이딩 만들기</button></div><div className="search"><Search size={18}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="지역 또는 코스 검색"/><button aria-label="검색어 지우기" onClick={() => setQuery('')}><X size={16}/></button></div><div className="section-title"><h2>{tab === 'search' ? '검색 결과' : '지금 모집 중인 라이딩'}</h2><button onClick={() => setTab('search')}>전체 보기</button></div><div className="list">{rides.map(ride => <RideCard key={ride.id} ride={ride} onOpen={() => setSelected(ride)}/>)}{!rides.length && <p className="empty">조건에 맞는 라이딩이 없습니다.</p>}</div></section>
  return <main className="app-shell"><header><button onClick={() => { setTab('home'); setSelected(null) }} className="logo">RIDEMATE<span>라이딩 메이트</span></button><button className="bell" aria-label="알림">●</button></header>{content}{!selected && <nav>{([['home', '홈'], ['search', '탐색'], ['create', '만들기'], ['my', '내 라이딩'], ['profile', '프로필']] as [Tab, string][]).map(([id, label]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'current' : ''}>{id === 'create' ? <Plus size={22}/> : id === 'search' ? <Search size={21}/> : id === 'profile' ? <CircleUserRound size={21}/> : id === 'my' ? <CalendarDays size={21}/> : <Route size={21}/>}<span>{label}</span></button>)}</nav>}</main>
}
